obstacle_range: 2.5
raytrace_range: 3.0

#robot_radius: ir_of_robot
inflation_radius: 0.4
obstacles_layer:
  observation_sources: point_cloud_sensor
  point_cloud_sensor: {sensor_frame: body, data_type: PointCloud2, topic: /detector/obstacle, marking: true, clearing: false}