global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  inflation_radius: 1.0
  rolling_window: false
  transform_tolerance: 0.5
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    enabled: true  
    observation_sources: point_cloud_sensor  
    point_cloud_sensor:
      sensor_frame: body  
      data_type: PointCloud2
      topic: /detector/obstacle  
      marking: true
      clearing: false